=== dev-cuttlefish/cuttlefish/src-old/ch/ethz/sg/cuttlefish/resources/configuration.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.sg.ethz.ch/research/cuttlefish/configuration.xsd"
	xmlns:cf="http://www.sg.ethz.ch/research/cuttlefish/configuration.xsd">



	<xs:element name="Configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="GUI" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Tab" minOccurs="0"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Widget"
											minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element
														name="Argument" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension
																	base="xs:string">
																	<xs:attribute
																		name="name" type="xs:string" use="required" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute
													name="name" type="xs:string" use="required" />
												<xs:attribute
													name="class" type="xs:string" use="required" />
												<xs:attribute name="id"
													type="xs:ID" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name"
										type="xs:string" use="required" />
									<xs:attribute name="condition"
										type="xs:string" use="required" />
									<xs:attribute name="id" type="xs:ID"
										use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>

					</xs:complexType>
				</xs:element>
				<xs:element name="Arguments" minOccurs="1"
					maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Argument" minOccurs="0"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension
											base="xs:string">
											<xs:attribute name="name"
												type="xs:string" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dev-cuttlefish/cuttlefish/dist/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>

<cf:Configuration
	xmlns:cf="http://www.sg.ethz.ch/research/cuttlefish/configuration.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sg.ethz.ch/research/cuttlefish/configuration.xsd src/ch/ethz/sg/cuttlefish/resources/configuration.xsd ">
	<GUI>
		<Tab id="Data" condition="*" name="Data">
			<Widget id="Import" name="Import"
				class="ch.ethz.sg.cuttlefish.gui.widgets.DataSourcePanel">
				<Argument name="sources">/home/ptsankov/eth/cuttlefish/testing-gui/datasources.xml</Argument>
			</Widget>
			<Widget id="Export" name="Export"
				class="ch.ethz.sg.cuttlefish.gui.widgets.ExportPanel" />
		</Tab>

		<Tab name="Simulation"
			condition="ch.ethz.sg.cuttlefish.networks.ISimulation"
			id="Simulation">
			<Widget name="Control"
				class="ch.ethz.sg.cuttlefish.gui.widgets.SimulationPanel"
				id="Control" />
		</Tab>
<!--
                <Tab name="Static cxf Network" id="CxfNetwork" condition="ch.ethz.sg.cuttlefish.networks.StaticCxfNetwork">
                        <Widget name="Load cxf file" class="ch.ethz.sg.cuttlefish.gui.widgets.CxfNetworkPanel" id="CxfNetworkPanel"></Widget></Tab>
		<Tab name="Pajek Network" id="PajekNetwork" condition="ch.ethz.sg.cuttlefish.networks.PajekNetwork">
			<Widget name="Load Pajek File" class="ch.ethz.sg.cuttlefish.gui.widgets.PajekPanel" id="PajekPanel"></Widget></Tab>
		<Tab name="GraphML Network" id="GraphML" condition="ch.ethz.sg.cuttlefish.networks.GraphMLNetwork">
			<Widget name="Load GraphML File" class="ch.ethz.sg.cuttlefish.gui.widgets.GraphMLPanel" id="GraphMLPanel"></Widget></Tab>
		<Tab name="User Network" id="UserNetwork" condition="ch.ethz.sg.cuttlefish.networks.UserNetwork">
			<Widget name="Load cff File" class="ch.ethz.sg.cuttlefish.gui.widgets.UserNetworkPanel" id="UserNetworkPanel"></Widget></Tab>
		<Tab name="Interactive cxf Network" id="InteractiveCxfNetwork" condition="ch.ethz.sg.cuttlefish.networks.InteractiveCxfNetwork">
			<Widget name="Load cxf file" class="ch.ethz.sg.cuttlefish.gui.widgets.InteractiveCxfNetworkPanel" id="ICxfNetworkPanel"></Widget>
			<Widget name="Load cef instructions" class="ch.ethz.sg.cuttlefish.gui.widgets.CefInstructionPanel" id="InstructionPanel"></Widget>
		</Tab>
-->
		<Tab name="Database Browsing" id="DBNetwork" condition="ch.ethz.sg.cuttlefish.networks.DBNetwork">
			<Widget name="Connect to DataBase" class="ch.ethz.sg.cuttlefish.gui.widgets.DBConnectPanel" id="DBConnectPanel"></Widget>
			<Widget name="Execute query" class="ch.ethz.sg.cuttlefish.gui.widgets.DBQueryPanel" id="DBQueryPanel"></Widget>
			<Widget name="Filter network" class="ch.ethz.sg.cuttlefish.gui.widgets.DBFilterPanel" id="DBFilterPanel"></Widget>
			<Widget name="Browse network" class="ch.ethz.sg.cuttlefish.gui.widgets.DBBrowsePanel" id="DBBrowsePanel"></Widget>			
			<Widget name="Expand vertices" class="ch.ethz.sg.cuttlefish.gui.widgets.DBExpandPanel" id="DBExpandPanel"></Widget></Tab>			
	</GUI>
	<Arguments>

	</Arguments>
</cf:Configuration>

=== dev-cuttlefish/cuttlefish/configurationNWR.xml
<?xml version="1.0" encoding="UTF-8"?>

<cf:Configuration
	xmlns:cf="http://www.sg.ethz.ch/research/cuttlefish/configuration.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sg.ethz.ch/research/cuttlefish/configuration.xsd src/ch/ethz/sg/cuttlefish/resources/configuration.xsd ">
	<GUI>
		<Tab id="data" condition="*" name="data">
			<Widget id="source" name="Source"
				class="ch.ethz.sg.cuttlefish.gui.widgets.DataSourcePanel">
				<Argument name="sources">datasourcesNWR.xml</Argument>
			</Widget>
			
			<Widget id="networkt" name="Networkt"
				class="ch.ethz.sg.Main.gui.NetworkPanel">
				<Argument name="nwtype">BB,SCC,NW</Argument>
			</Widget>
			
			<Widget id="country" name="Country"
				class="ch.ethz.sg.Main.gui.CountryPanel">
				<!--
				<Argument name="countries">AU,BM,BR,CA,CH,CN,DE,ES,FI,FR,GB,GR,HK,ID,IL,IN,IT,JP,KR,KY,NO,PE,PH,PL,PT,RU,SE,SG,TH,TW,US,ZA,CHTot</Argument>
				-->
				<Argument name="countries">AE,AR,AT,AU,BE,BM,CA,CH,CL,CN,DE,DK,ES,FI,FR,GB,GR,HK,ID,IE,IL,IN,IS,IT,JO,JP,KR,KW,KY,LU,MX,MY,NL,NO,NZ,OM,PH,PT,SA,SE,SG,TH,TN,TR,TW,US,VG,ZA</Argument>
			</Widget>
			
			<Widget id="export" name="export"
				class="ch.ethz.sg.cuttlefish.gui.widgets.ExportPanel" />
			<Widget id="animation" name="animation"
				class="ch.ethz.sg.cuttlefish.gui.widgets.AnimationPanel">
				<Argument name="folder">animations</Argument></Widget>
		</Tab>

		<Tab id="network" condition="*" name="network">
			<Widget id="metrics" name="metrics"
				class="ch.ethz.sg.cuttlefish.gui.widgets.NetworkMetricPanel" />
			<Widget id="edges" name="edges"
				class="ch.ethz.sg.cuttlefish.gui.widgets.EdgePanel" />
			<Widget id="date" name="date"
				class="ch.ethz.sg.cuttlefish.gui.widgets.DatePanel" />
		</Tab>


		<Tab name="simulation"
			condition="ch.ethz.sg.cuttlefish.networks.ISimulation"
			id="simulation">
			<Widget name="control"
				class="ch.ethz.sg.cuttlefish.gui.widgets.SimulationPanel"
				id="control" />
		</Tab>
	</GUI>
	<Arguments>
		<Argument name="layoutFolder">pos/</Argument>
	</Arguments>
</cf:Configuration>

=== dev-cuttlefish/cuttlefish/cuttlefish0.1/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>

<cf:Configuration
	xmlns:cf="http://www.sg.ethz.ch/research/cuttlefish/configuration.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sg.ethz.ch/research/cuttlefish/configuration.xsd src/ch/ethz/sg/cuttlefish/resources/configuration.xsd ">
	<GUI>
		<Tab id="Data" condition="*" name="Data">
			<Widget id="import" name="Import"
				class="ch.ethz.sg.cuttlefish.gui.widgets.DataSourcePanel">
				<Argument name="sources">datasources.xml</Argument>
			</Widget>
			<Widget id="export" name="export"
				class="ch.ethz.sg.cuttlefish.gui.widgets.ExportPanel" />
		</Tab>

		<Tab id="network" condition="*" name="network">
			<Widget id="metrics" name="metrics"
				class="ch.ethz.sg.cuttlefish.gui.widgets.NetworkMetricPanel" />
			<Widget id="edges" name="edges"
				class="ch.ethz.sg.cuttlefish.gui.widgets.EdgePanel" />
			<Widget id="date" name="date"
				class="ch.ethz.sg.cuttlefish.gui.widgets.DatePanel" />
		</Tab>


		<Tab name="simulation"
			condition="ch.ethz.sg.cuttlefish.networks.ISimulation"
			id="simulation">
			<Widget name="control"
				class="ch.ethz.sg.cuttlefish.gui.widgets.SimulationPanel"
				id="control" />
		</Tab>
	</GUI>
	<Arguments>

	</Arguments>
</cf:Configuration>

=== dev-cuttlefish/cuttlefish/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>

<cf:Configuration
	xmlns:cf="http://www.sg.ethz.ch/research/cuttlefish/configuration.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sg.ethz.ch/research/cuttlefish/configuration.xsd src/ch/ethz/sg/cuttlefish/resources/configuration.xsd ">
	<GUI>
		<Tab id="Data" condition="*" name="Data">
			<Widget id="Import" name="Import"
				class="ch.ethz.sg.cuttlefish.gui.widgets.DataSourcePanel">
				<Argument name="sources">datasources.xml</Argument>
			</Widget>
			<Widget id="Export" name="Export"
				class="ch.ethz.sg.cuttlefish.gui.widgets.ExportPanel" />
		</Tab>

		<Tab id="Network" condition="*" name="Network">
		</Tab>


		<Tab name="Simulation"
			condition="ch.ethz.sg.cuttlefish.networks.ISimulation"
			id="Simulation">
			<Widget name="Control"
				class="ch.ethz.sg.cuttlefish.gui.widgets.SimulationPanel"
				id="Control" />
		</Tab>
		<Tab name="Pajek Network" id="PajekNetwork" condition="ch.ethz.sg.cuttlefish.networks.PajekNetwork">
			<Widget name="Load Pajek File" class="ch.ethz.sg.cuttlefish.gui.widgets.PajekPanel" id="PajekPanel"></Widget></Tab>
		<Tab name="GraphML Network" id="GraphML" condition="ch.ethz.sg.cuttlefish.networks.GraphMLNetwork">
			<Widget name="Load GraphML File" class="ch.ethz.sg.cuttlefish.gui.widgets.GraphMLPanel" id="GraphMLPanel"></Widget></Tab>
		<Tab name="User Network" id="UserNetwork" condition="ch.ethz.sg.cuttlefish.networks.UserNetwork">
			<Widget name="Load cff File" class="ch.ethz.sg.cuttlefish.gui.widgets.UserNetworkPanel" id="UserNetworkPanel"></Widget></Tab>
	</GUI>
	<Arguments>

	</Arguments>
</cf:Configuration>
