=== dev-cuttlefish/cuttlefish/src-old/ch/ethz/sg/cuttlefish/resources/datasources.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.sg.ethz.ch/research/cuttlefish/datasources.xsd"
	xmlns:cf="http://www.sg.ethz.ch/research/cuttlefish/datasources.xsd">



	<xs:element name="DataSources">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Source"  minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Argument" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension
											base="xs:string">
											<xs:attribute name="name"
												type="xs:string" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:ID"
							use="required" />
						<xs:attribute name="name" type="xs:string"
							use="required" />
						<xs:attribute name="class" type="xs:string"
							use="required" />
						<xs:attribute name="login" type="xs:string"
							use="optional" />
						<xs:attribute name="password" type="xs:string"
							use="optional" />
						<xs:attribute name="host" type="xs:string"
							use="optional" />
						<xs:attribute name="database" type="xs:string"
							use="optional" />
						<xs:attribute name="group" type="xs:string"
							use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>






</xs:schema>

=== dev-cuttlefish/cuttlefish/dist/datasources.xml
<?xml version="1.0" encoding="UTF-8"?>
<cf:DataSources xmlns:cf="http://www.sg.ethz.ch/research/cuttlefish/datasources.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sg.ethz.ch/research/cuttlefish/datasources.xsd datasources.xsd ">
	<Source id="staticCxfNetwork"
		class="ch.ethz.sg.cuttlefish.networks.StaticCxfNetwork" name="Load cxf network">
	</Source>
	<Source id="cxfNetwork" name="Interactive cxf network" class="ch.ethz.sg.cuttlefish.networks.InteractiveCxfNetwork"></Source>
	<Source id="pajekNet" name="Pajek load" class="ch.ethz.sg.cuttlefish.networks.PajekNetwork"></Source>
	<Source id="graphML" name="GraphML load" class="ch.ethz.sg.cuttlefish.networks.GraphMLNetwork"></Source>
	<Source id="userNetwork" name="Load cff Network" class="ch.ethz.sg.cuttlefish.networks.UserNetwork"></Source>
	<Source id="sim1" name="Test Simulation" class="ch.ethz.sg.cuttlefish.networks.TestSimulation">
		<Argument name="test">Argument</Argument>
		<Argument name="alpha">10.0</Argument></Source>
	<Source id="sim2" name="BA Simulation" class="ch.ethz.sg.cuttlefish.networks.BASimulation"></Source>
</cf:DataSources>

=== dev-cuttlefish/cuttlefish/src/ch/ethz/sg/cuttlefish/resources/default_datasources.xml
<?xml version="1.0" encoding="UTF-8"?>
<cf:DataSources xmlns:cf="http://www.sg.ethz.ch/research/cuttlefish/datasources.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sg.ethz.ch/research/cuttlefish/datasources.xsd datasources.xsd ">
	<Source id="selectInput" class="selectInput" name="Select input"></Source>
	<Source id="staticCxfNetwork"
		class="ch.ethz.sg.cuttlefish.networks.StaticCxfNetwork" name="CXF network">
	</Source>
	<Source id="cxfNetwork" name="Interactive CXF network" class="ch.ethz.sg.cuttlefish.networks.InteractiveCxfNetwork"></Source>
	<Source id="Database" name="Database network" class="ch.ethz.sg.cuttlefish.networks.DBNetwork"></Source>
	<Source id="pajekNet" name="Pajek network" class="ch.ethz.sg.cuttlefish.networks.PajekNetwork"></Source>
	<Source id="graphML" name="GraphML network" class="ch.ethz.sg.cuttlefish.networks.GraphMLNetwork"></Source>
	<Source id="userNetwork" name="CFF network" class="ch.ethz.sg.cuttlefish.networks.UserNetwork"></Source>
	<Source id="sim1" name="Test simulation" class="ch.ethz.sg.cuttlefish.networks.TestSimulation">
		<Argument name="test">Argument</Argument>
		<Argument name="alpha">10.0</Argument></Source>
	<Source id="sim2" name="BA simulation" class="ch.ethz.sg.cuttlefish.networks.BASimulation"></Source>
</cf:DataSources>
